- name: Destroy clusters UPI on KVM
  hosts: localhost
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Wait for LB to get an IP address
      community.libvirt.virt:
        command: list_vms
      register: allvms

    # TODO: FIX it
    - name: Remove all vms
      community.libvirt.virt:
        command: undefine
        force: true
        name: "{{ item }}"
      loop: "{{ allvms.list_vms }}"
      when: item is search("{{ clustername }}")

    - name: Delete all network files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/NetworkManager/dnsmasq.d/{{ clustername }}.conf"
        - "/etc/dnsmasq.{{ clustername }}.addnhosts"
        - "/{{ clusters_dir }}/{{ clustername }}/"
