- name: Destroy clusters UPI on KVM
  hosts: localhost
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Get a list of all virtual machines
      ansible.builtin.command: virsh list --all --name
      register: vms
      changed_when: vms.rc == 0

    - name: Filter VMs containing 'clustername' in their names
      ansible.builtin.set_fact:
        allvms: "{{ vms.stdout_lines | select('search', clustername) }}"

    - name: Remove all vms
      community.libvirt.virt:
        command: destroy
        force: true
        name: "{{ item }}"
      loop: "{{ allvms }}"
      ignore_errors: true

    - name: Delete all network files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      register: deletefiles
      with_items:
        - "/etc/NetworkManager/dnsmasq.d/{{ clustername }}.conf"
        - "/etc/dnsmasq.{{ clustername }}.addnhosts"
        - "/{{ clusters_dir }}/{{ clustername }}/"

    - name: Restart libvirt when configuring dnsmasq
      ansible.builtin.service:
        name: libvirtd
        state: restarted
      when: deletefiles.changed

    - name: Restart NetworkManager when configuring dnsmasq
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
      when: deletefiles.changed
